server:
  port: 8761

eureka:
  datacenter: trmap
  environment: product
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/

    healthcheck:
      enabled: true
#spring:
#  security:
#    basic:
#      enabled: true
#    user:
#      name: root
#      password: 123